version: '3.7'

services: 
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    ports: 
      - 3000:3000
    volumes:
      - ./frontend:/app
  
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    environment:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB

  postgres_db:
    image: postgres:14
    container_name: postgres_db
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
volumes:
  db-store: