version: '3.7'

services: 
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    ports: 
      - 3000:3000
    volumes:
      - ./frontend:/app
  
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app